#EdibleEggs configuration file
#
#This configuration file specifies the effects that a player
# can get from eating a raw egg.
#
#Use this link as a reference for a list of effects and effect names
#http://minecraft.gamepedia.com/Data_values#Status_effects
#Use this link as a reference for information about each effect
#http://minecraft.gamepedia.com/Status_effect#List_of_effects
#
#Configuration format is as follows:
#
#notifyOnAvailableUpdate: <true or false>
#rawEggRestoreSaturation: <Float saturation>
#rawEggRestoreHunger: <Integer (1 is half of a drumstick on the HUD)>
#roastedEggRestoreSaturation: <Float saturation>
#roastedEggRestoreHunger: <Integer (1 is half of a drumstick on the HUD)>
#rawEggEffects:
#  <Effect Name>:
#    chance: <integer from 1-100>
#    amplifier: <amplifier>
#    duration: <seconds>
#  <Effect Name>:
#    chance: <integer from 1-100>
#    amplifier: <amplifier>
#    duration: <seconds>
#
#Any amount of effects can be added/removed.
#
#If the chances of all defined effects add up to more than
#100, an exception is thrown. If the chances add up to less
#than 100, the remainder is the chance that no effect will
#be applied.