notifyOnAvailableUpdate: true
rawEggRestoreSaturation: 0.8
rawEggRestoreHunger: 1
roastedEggRestoreSaturation: 1
roastedEggRestoreHunger: 1
rawEggEffects:
  hunger:
    chance: 40
    amplifier: 2
    duration: 20
  poison:
    chance: 10
    amplifier: 1
    duration: 10